openapi: 3.0.0
info:
  description: Prin acest API care e RESTful, un administrator sau un utilizator logat
    poate obtine si gestiona datele personale si ale cursurilor disponibile.
  title: API pentru utilizatori SkiVI
  version: 1.0.0
servers:
- url: http://localhost:8088/skivi_war_exploded
security:
- cookieAuth: []
paths:
  /users:
    get:
      description: Intoarce lista cu numele si descrierea tuturor utilizatorilor
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
          description: Am returnat cu succes toti utilizatorii din aplicatie
        "403":
          description: Daca clientul ce a depus cererea nu are dreptul de administrator,
            lista utilizatorilor nu este disponibila
      tags:
      - Users
      x-accepts: application/json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "201":
          description: Cererea de creare utilizator a fost efectuata cu succes
      tags:
      - Users
      x-contentType: application/json
      x-accepts: application/json
  /users/{id}:
    delete:
      description: Sterge user-ul aflat la acel id.
      parameters:
      - description: Id utilizator.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          description: Utilizatorul a fost sters cu succes.
      tags:
      - User
      x-accepts: application/json
    get:
      description: Intoarce numele si descrierea utilizatorului de la un id
      parameters:
      - description: Id utilizator.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Am returnat cu succes acel utilizator
        "403":
          description: Daca clientul ce a depus cererea nu are dreptul de administrator,
            sau nu este insusi utilizatorul cerut, datele nu sunt disponibile
        "404":
          description: Daca nu exista un client cu acest id
      x-accepts: application/json
    patch:
      description: Actualizeaza user-ul aflat la acel id partial conform a ceea ce
        este descris in corpul cererii in format JSON.
      parameters:
      - description: Id utilizator.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: A fost actualizat partial userul cu succes.
      tags:
      - Users
      x-contentType: application/json
      x-accepts: application/json
    put:
      description: O suprascriere totala a utilizatorului aflat la acel id folosindu-se
        de ceea ce este in corpul cererii (un User in JSON)
      parameters:
      - description: Id utilizator.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: A fost suprascris utilizatorul cu succes.
      tags:
      - Users
      x-contentType: application/json
      x-accepts: application/json
  /users/{id}/skills:
    get:
      description: Intoarce datele despre cursurile la care utilizatorul descris de
        id s-a inscris
      parameters:
      - description: Id utilizator.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/inline_response_200'
                type: array
          description: Am returnat cu succes datele despre prezentarea acelor cursuri
        "403":
          description: Daca clientul ce a depus cererea nu are dreptul de administrator,
            sau nu este insusi utilizatorul cerut, datele nu sunt disponibile
        "404":
          description: Daca nu exista un client cu acest id
      x-accepts: application/json
components:
  schemas:
    User:
      example:
        password: password
        admin: true
        description: description
        email: email
        username: username
      properties:
        email:
          type: string
        password:
          type: string
        username:
          type: string
        admin:
          type: boolean
        description:
          type: string
      required:
      - admin
      - description
      - email
      - password
      - username
      type: object
    Users:
      items:
        $ref: '#/components/schemas/User'
      type: array
    inline_response_200:
      example:
        name: name
        url: url
      properties:
        name:
          type: string
        url:
          type: string
      required:
      - name
      - url
  securitySchemes:
    cookieAuth:
      in: header
      name: Authorization
      type: apiKey

